name: CI
on: [push, pull_request]
jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Smoke check
        run: python - <<'PY'
from scraper import main
print("Running scraper smoke check (no network calls).")
print("OK: import and main() defined.")
PY
